version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-sdk
    versions:
    - "> 2.658.0, < 3"
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: rollbar
    versions:
    - 2.20.0
    - 2.21.0
