language: node_js
node_js:
  - "8" 

install:
  - npm i -g lerna greenkeeper-lockfile@1
  - lerna bootstrap

before_script: greenkeeper-lockfile-update

script:
  - lerna run lint
  - lerna run test

after_script: greenkeeper-lockfile-upload

notifications:
  email: false
  slack:
    secure: 4sxvqpVlGs8jqTrgU8BTvuJ4S87oiGssY8g/faXoHV+eVChNZahBlMa7RWH5e7VgUu2kHp0Y3G7Fkyk85Kg+/rRUu9333YQ3adM6jwxEaKeUjOLkBM8lwekb0FmlK3mzgmiwU7t23WGbQZr8YmIuhzbE5zsBwtb4LNBhojCdvsoq1BwfWCiHpqRj3TO5RgjvFHhpXHf60yx73Ff3LazkQb/qk9nhjF9dxWRhV5MBN0YOqBugm4rEuYk1gsPxbaPbdAw0n+UbZi8FKJjCseTTocCN5gggrUyS1xycnZ99lIeQDX3F+qwVfXvPHLXDKGRZJFmqaQ1lm/Gn38x0ACmWxqgHG3jF8WxU47UkGIxrrIBOCjTDZZ0mtS4tEZ9077bZO+Ja9UT3stYjtQ4Y7HGF8GKzI0x7HlcatpWpNZjbXtsYqjOCI4qJCH2LqET90W1W/NGVcFPGSFQXHzYouJkL7GRcxXpc1dJqrJbKO9fU+0FhOK8YJ4LETKOc3TAmPvA4hHlnIBnZIEnh7mc5YuSk2HVs1hgKCyMiViBcXafYsHFO7QPOPMk63qebL8N0R5lzRLSHkKtzLD2igB3ACt/8DDA13Qus32W+dPg9E3s/YDcR6wnplO5IqL17Lj2Br4JNYOvA/QGrZ0CTWS1KwyuJ8uTYGkT8fBlC2H4uLzr30kQ=
