language: node_js
node_js:
- 4
notifications:
  email: false
addons:
  code_climate:
    repo_token: f5c649e2bc99b0a32cadebf588b3b078ecc05a55f58ae37b342b6777b0117f0a
after_script:
- npm install -g codeclimate-test-reporter
- cat lcov.info | codeclimate-test-reporter
